### ISSUE TITLE
HDL-in node emits wrong msg?

### ISSUE THREAD

**Issue by KukuruzaAndrii** [estbeetoo/node-red-contrib-hdl#1]
Hello, thanks for library.

 I use HDL-out node, and it works great. I can send any command.
But, when i try to read HDL bus from HDL-in node, i receive this msg
``` 
{ 
    topic: "[object Object]", 
    payload: "01", 
    sender: object, 
    type: "command", 
    _msgid: "2f784928.011606" 
}
```
Node info says:
>msg.topic will be:
>- 'read': when a read request arrives on the bus
>- 'respond': when another HDL device responds to a read request on the bus
>- 'write': when somebody writes a value to a HDL group address.

>msg.payload will have the format: {width: X, value: Y}
>- srcphy: source physical address (eg.'1.1.100')
>- dstgad: destination group address (eg.'1/2/3')
>- value: the actual value received
>- dpt: the datapoint type bits of the telegram

What am i doing wrong?

**Comment by aborovsky** [comment]
Hi, @KukuruzaAndrey.
We are glad that our node library is extremely useful for you!

May I ask you to enable proper debug messaging?
You should to start node-red with DEBUG environment parameter:

DEBUG=node-red-contrib-hdl

Read more hot to do that in your OS here: https://www.npmjs.com/package/debug

Repeat your case and send log file here, please.

P.S.: I am able to reproduce it by myself with HDL equipment, on Monday, not earlier.

**Comment by KukuruzaAndrii** [comment]
Thank for the fast reply!
I enable debug messaging, and see this:
![image](https://cloud.githubusercontent.com/assets/16447219/24323586/9add25e2-1180-11e7-9934-062573ab94ea.png)
I'm not out of time, so do it when you feel comfortable.

**Comment by ykornilov** [comment]
Andrey, hello!
Try it now, please.

**Comment by KukuruzaAndrii** [comment]
Hello, @ykornilov! 
I try to use new version, and see this:
![image](https://cloud.githubusercontent.com/assets/16447219/25062267/2a662bee-21d2-11e7-9d00-05252f9a14eb.png)

msg.topic looks more informative now, thank you.

But this information still makes sense?
>Node info says:
>>msg.topic will be:
>>- 'read': when a read request arrives on the bus
>>- 'respond': when another HDL device responds to a read request on the bus
>>- 'write': when somebody writes a value to a HDL group address.
>
>>msg.payload will have the format: {width: X, value: Y}
>>- srcphy: source physical address (eg.'1.1.100')
>>- dstgad: destination group address (eg.'1/2/3')
>>- value: the actual value received
>>- dpt: the datapoint type bits of the telegram

**Comment by ykornilov** [comment]
Andrey, thank you for your comment!
The information was left with another of our nodes - under the KNX.
Corrected!
