### ISSUE TITLE
Support for raw commands

### ISSUE THREAD

**Issue by haydendonald** [estbeetoo/node-red-contrib-hdl#3]
Hi this is not really an issue as such but could you possibly add the ability to send raw commands to the HDL bus?

For example when sending 0x02 the node will return an error saying not implemented.
It can be super simple just add the ability to send the command, and a buffer of data elements.
That way a user can send Operate:0x02, Area:1, Scene:1 etc, as well as control wall panels.

Also more of an issue possibly.. I cannot get any information from the bus (could be the same thing as above) but if you press a wall panel nothing comes though the HDL input

Thanks lots :)

**Comment by ykornilov** [comment]
Hi!
Sorry that I did not reply for a while.
I really like your idea, but now there is not enough time to implement it.
To get more functionality, try replacing the string
```"smart-bus": "^0.2.0",```
on
```"smart-bus": "https://github.com/estbeetoo/smart-bus.git",```
in the file ```package.json``` and reinstall it
