### ISSUE TITLE
HDL bus error on send: Error: Data encoder for command 0xECT] not implemented

### ISSUE THREAD

**Issue by barkrakk** [estbeetoo/node-red-contrib-hdl#4]
Hi,

Im' just trying to send following command by hdl-out node:

![image](https://user-images.githubusercontent.com/10454148/39599620-9300745c-4f1c-11e8-8424-7260a71b28a1.png)

![image](https://user-images.githubusercontent.com/10454148/39600430-01f2f5fe-4f1f-11e8-9e61-7557fc527c00.png)

There is no initialization of connection to HDL controller. Following error is reported: _HDL bus error on send: Error: Data encoder for command 0xECT] not implemented_

Not sure if that relates to operation code 49 in any way.

![image](https://user-images.githubusercontent.com/10454148/39599486-447c245c-4f1c-11e8-837d-9fd5e47519d3.png)

![image](https://user-images.githubusercontent.com/10454148/39600676-c61d4402-4f1f-11e8-869d-a9fdf8020b00.png)

I have installed DEBUG, but not sure how to start node-red with that enabled.

The HDL controller is configure like this:

![image](https://user-images.githubusercontent.com/10454148/39599939-905b9320-4f1d-11e8-8bd1-bab772f14f09.png)

DeviceID for the HDL IP gateway is set to 99, as default. Not sure if 99 is correct, as I don't know if that is configurable.

Is there any obvious wrong how I have configured the flow? Or is this a issue?

**Comment by aborovsky** [comment]
Thank you for reporting!
I assume: there are error in your configuration about msg.payload.
You use JSON payload inside of Inject node.
It's content should be equal to:

```json
{
    "code": 49,
    "data":  {
        "channel": 6,
        "level": 100,
    }
}
```
![image](https://user-images.githubusercontent.com/1669420/39616885-35ecbe0a-4f86-11e8-83d0-fb7bd73feb35.png)


And topic `1.103` should be defined in proper field:
![image](https://user-images.githubusercontent.com/1669420/39616877-29f897a4-4f86-11e8-99f5-03d5b4be2103.png)

**Comment by barkrakk** [comment]
Thanks. I got this to work.

![image](https://user-images.githubusercontent.com/10454148/39839638-04dba3c0-53dd-11e8-9b1e-af61a8a255b4.png)


Dimmer Level value is input to the function node, where the required JSON object is build up.  Like this:

```   
var dim_level = Number(msg.payload);

msg.topic = "1.103"
msg.payload = {  
      code: 49,
      data: {
        channel: 6,
        level: dim_level
      }
   }

return msg;
```

I can then manipulate a Dimmer Item in OpenHab, and use Node-Red to send that value to the HDL controller.
