### ISSUE TITLE
HDL-in node - how to read payload

### ISSUE THREAD

**Issue by barkrakk** [estbeetoo/node-red-contrib-hdl#5]
Hi,

I have a functional HDL-out node, where I can manipulate a dimmer channel from OpenHab UI.

How can the HDL-in node be used to read the dimming level on the same channel? If someone set dimming value from physical switch on the wall, I would then read that value and update OpenHab UI with the current value.

Is that possible with the HDL-in node? And how would I extract the values from the payload? I don't see from the debug, where the data is stored:

![image](https://user-images.githubusercontent.com/10454148/39840611-4b6e654a-53e0-11e8-98a2-af780f09c0cf.png)

**Comment by aborovsky** [comment]
Yes, it's possible. Once physical switch sets some dim level, you able to "hear" this command on HDL gateway and listen for this command with HDL-in.

The value should be accessible with `msg.payload`, as far as i know.

**Comment by aborovsky** [comment]
@barkrakk may i ask you to provide full msg logged in debug tab?
